name: coverage

on: [push, pull_request]

jobs:
  run:
    name: Coverage Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip install pyfaidx==0.5.8
          pip install pytest
          pip install gcovr

      - name: Generate coverage report
        run: |
          python setup.py build_ext -i
          pytest tests
          gcovr --filter src/ --xml -o coverage.xml
        env:
          CFLAGS: --coverage

      - name: Upload Coverage to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
